#!/usr/bin/env bash
for file_name in ~/files_to_clean/*.csv;
do
    lines=$(head -n $1 $file_name)
    rm $file_name
    for line in $lines;
    do
        if [ ! -e $file_name ]
        then
            # storing file lines turns LF bytes into CR. tr turns the CR back into LF
            echo -n $line | tr '\r' '\n' > $file_name
        else
            echo -n $line | tr '\r' '\n' >> $file_name
        fi
    done
done
